version: '3.8'


services:
    # image project
    app-livewire:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis-livewire
        networks:
            - livewire

    # nginx
    nginx-livewire:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8700:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - livewire

    # db mysql
    db-livewire:
        image: mysql:8.0
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3355:3306"
        networks:
            - livewire

    # PHPMyAdmin
    phpmyadmin-livewire:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        networks:
            - livewire

    # redis
    redis-livewire:
        image: redis:latest
        networks:
            - livewire

networks:
    livewire:
        driver: bridge
